import { jsPDF } from "jspdf";
import { format } from "date-fns";

export type PdfOrder = {
  id: string;
  carName?: string;
  customerName?: string;
  customerEmail?: string;
  customerPhone?: string;
  startDate?: string;
  endDate?: string;
  createdAt?: {
    toDate?: () => Date;
  } | Date | string | number;
};

function toDate(value: {
  toDate?: () => Date;
} | Date | string | number | null | undefined): Date | null {
  if (!value) return null;
  if (value instanceof Date) return value;
  if (typeof value === "object" && typeof value?.toDate === "function") return value.toDate();
  if (typeof value === "number") return new Date(value);
  if (typeof value === "string") {
    const d = new Date(value);
    return Number.isNaN(d.getTime()) ? null : d;
  }
  return null;
}

export function downloadOrderPdf(order: PdfOrder) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });

  const createdDate = toDate(order.createdAt);
  const createdStr = createdDate ? format(createdDate, "dd.MM.yyyy HH:mm") : "-";

  const startStr = order.startDate || "-";
  const endStr = order.endDate || "-";

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Car Rental Order", 40, 60);

  doc.setDrawColor(30);
  doc.setLineWidth(1);
  doc.line(40, 75, 555, 75);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");

  const lines: Array<[string, string]> = [
    ["Order ID", order.id],
    ["Car", order.carName || "-"],
    ["Customer", order.customerName || "-"],
    ["Email", order.customerEmail || "-"],
    ["Phone", order.customerPhone || "-"],
    ["From", startStr],
    ["To", endStr],
    ["Ordered at", createdStr],
  ];

  let y = 110;
  for (const [label, value] of lines) {
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, 40, y);
    doc.setFont("helvetica", "normal");
    doc.text(String(value), 170, y);
    y += 24;
  }

  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text("Generated by drivingCar", 40, 800);

  const safeName = (order.customerName || "order").replace(/[^a-z0-9_-]+/gi, "_");
  doc.save(`order_${safeName}_${order.id}.pdf`);
}
